spring.application.name=LNPbackend


# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/learnplay
spring.datasource.username=root
spring.datasource.password=dsadsa
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

Access-Control-Allow-Origin: your-frontend-domain
Access-Control-Allow-Credentials: true

# JWT Settings
jwt.expiration=36000000
# 10 hours in milliseconds
jwt.refresh-expiration=604800000
# 7 days in milliseconds

## Gemini Config
gemini.api.key=AIzaSyDy355m1zjIa09WBWQh5-kQG-PX8aiJ7rk
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=AIzaSyDy355m1zjIa09WBWQh5-kQG-PX8aiJ7rk